// <auto-generated />
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210525154924_Initial Seed Data")]
    partial class InitialSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("App.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GradeNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "English",
                            GradeNum = 80m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Math",
                            GradeNum = 60m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Science",
                            GradeNum = 75m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Government",
                            GradeNum = 90m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "English",
                            GradeNum = 100m,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("App.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 15,
                            ClassYear = 0,
                            FirstName = "Mark",
                            LastName = "Flores"
                        },
                        new
                        {
                            Id = 2,
                            Age = 16,
                            ClassYear = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            Age = 17,
                            ClassYear = 2,
                            FirstName = "Jessica",
                            LastName = "Robinson"
                        },
                        new
                        {
                            Id = 4,
                            Age = 18,
                            ClassYear = 3,
                            FirstName = "Rex",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Age = 18,
                            ClassYear = 3,
                            FirstName = "Amanda",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("App.Models.Grade", b =>
                {
                    b.HasOne("App.Models.Student", "Student")
                        .WithMany("GradesList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("App.Models.Student", b =>
                {
                    b.Navigation("GradesList");
                });
#pragma warning restore 612, 618
        }
    }
}
